# Data

## Description

I aim to explore Korea’s political polarization from an economic and generational perspective by conducting a reliable, national data-based analysis. The first data is the statistical data from the KOrean Statistical Information Service (KOSIS) operated by the Statistics Korea (KOSTAT) of the Republic of Korea, which provides Gross Regional Domestic Product, Gross Regional Income, and Personal Income per city and province, and it’s annually updated quantitative indicators of the economic level of 17 cities and provinces nationwide. The data is provided in CSV format, so it can be imported and used directly from the R environment. The second data is the result of the 20th presidential election collected and published by the National Election Commission of the Republic of Korea, which includes the number of votes and the vote share cast by political parties across the country and can be easily downloaded through the public data portal, such as data.go.kr. I’m also planning to use survey data released by public polling institutions such as Korea Research and Gallup as an auxiliary to compare voting propensity based on age group. However, due to the secret voting principle, the data on the vote share by age group does not exist directly. Therefore, the indirect pattern will be interpreted by combining the regional political orientation based on election statistics and the political attitude by age based on opinion polls. All data is provided by reliable official institutions of the Republic of Korea, and it’s accessible online and suitable for analysis purposes, ensuring sufficient validity and reproducibility for conducting exploratory visualization-based research.

## Missing value analysis
